### ISSUE TITLE
Namespace validation error for certificates issued by the GEANT Personal CA 4

### ISSUE THREAD

**Issue by andreaceccanti** [eu-emi/canl-java#105]
Hello,

INFN (like other institutions) recently switched from the Digicert CA to Sectigo.

We are observing TLS handshake issues on services where TLS is managed with CANL 2.5.0 and Firefox is the client:
https://issues.infn.it/jira/browse/STOR-1218

Firefox sends a chain of three certificates (Chrome and Safari OTOH only send the EEC):

```
[
  Version: V3
  Subject: CN=Andrea Ceccanti aceccant@infn.it, O=Istituto Nazionale di Fisica Nucleare, C=IT, DC=tcs, DC=terena, DC=org
  Signature Algorithm: SHA384withRSA, OID = 1.2.840.113549.1.1.12
  ...
  Validity: [From: Thu May 14 02:00:00 CEST 2020,
               To: Mon Jun 14 01:59:59 CEST 2021]
  Issuer: CN=GEANT eScience Personal CA 4, O=GEANT Vereniging, C=NL
  SerialNumber: [    318339d0 c217e634 99b5f273 74e76a62]
  ...
], 
[
  Version: V3
  Subject: CN=GEANT eScience Personal CA 4, O=GEANT Vereniging, C=NL
  Signature Algorithm: SHA384withRSA, OID = 1.2.840.113549.1.1.12
  ...
  Validity: [From: Tue Feb 18 01:00:00 CET 2020,
               To: Mon May 02 01:59:59 CEST 2033]
  Issuer: CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jersey City, ST=New Jersey, C=US
  SerialNumber: [    aa3272ee da1b19a6 37f6f256 2af4eef1]
  ...
],
[
Version: V3
  Subject: CN=USERTrust RSA Certification Authority, O=The USERTRUST Network, L=Jersey City, ST=New Jersey, C=US
  Signature Algorithm: SHA384withRSA, OID = 1.2.840.113549.1.1.12
  ...
  Validity: [From: Tue Mar 12 01:00:00 CET 2019,
               To: Mon Jan 01 00:59:59 CET 2029]
  Issuer: CN=AAA Certificate Services, O=Comodo CA Limited, L=Salford, ST=Greater Manchester, C=GB
  SerialNumber: [    3972443a f922b751 d7d36c10 dd313595]
  ...
]]
```

The validation of this chain fails on CANL due to a missing namespace definition problem, as shown in the 
following CANL validation error:

```
-----Certificate 1-----
X.509 v3 certificate, Subject: CN=Andrea Ceccanti aceccant@infn.it,O=Istituto Nazionale di Fisica Nucleare,C=IT,DC=tcs,DC=terena,DC=org, Issuer: CN=GEANT eScience Personal CA 4,O=GEANT Vereniging,C=NL

-----Certificate 2-----
X.509 v3 certificate, Subject: CN=GEANT eScience Personal CA 4,O=GEANT Vereniging,C=NL, Issuer: CN=USERTrust RSA Certification Authority,O=The USERTRUST Network,L=Jersey City,ST=New Jersey,C=US

-----Certificate 3-----
X.509 v3 certificate, Subject: CN=USERTrust RSA Certification Authority,O=The USERTRUST Network,L=Jersey City,ST=New Jersey,C=US, Issuer: CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB
. Error: Namespace definition for the certificate issuer (CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB) is not defined, and namespaces are configured to be required
```

The EGI trustanchors bundle does not include any information for the certificate issuer `CN=AAA Certificate Services,O=Comodo CA Limited,L=Salford,ST=Greater Manchester,C=GB`.

Shouldn't CANL validation only consider EEC and proxy certificates in the incoming chain and ignore any CA certs (that cannot be trusted)?

Thanks!

**Comment by maarten-litmaath** [comment]
+1: CA certs provided by the client must not be trusted.
If CANL needs that nonetheless for some use case,
there should be an option to switch it on explicitly...

**Comment by maarten-litmaath** [comment]
That said, in IGTF the problematic cert is **NOT** signed by that missing CA:

$ openssl x509 -noout -subject -issuer -in USERTrustRSACertificationAuthority.pem 
subject= /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
issuer= /C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority

Is the client installation out of date?

**Comment by maarten-litmaath** [comment]
That change happened in March this year:

https://dist.igtf.net/distribution/igtf/current/CHANGES

**Comment by andreaceccanti** [comment]
Hello @maarten-litmaath, 

the client here is Firefox, so probably the out of date CA bundle is the one embedded inside Firefox?

**Comment by maarten-litmaath** [comment]
Ciao Andrea,
in my FF (78.0.2) on MacOS that certificate is self-signed...

**Comment by andreaceccanti** [comment]
My FF (79.0) on MacOS has both certs, the self-signed one:

![Schermata 2020-07-29 alle 16 27 58](https://user-images.githubusercontent.com/1152853/88813407-2f3e7a00-d1b9-11ea-989e-6bdb1c4d2d7a.png)

and the intermediate one:

![Schermata 2020-07-29 alle 16 30 17](https://user-images.githubusercontent.com/1152853/88813430-34032e00-d1b9-11ea-890b-bb2f871706d2.png)

And Firefox during the handshake apparently sends the wrong one...

**Comment by maarten-litmaath** [comment]
Ciao Andrea,
I suppose I missed the other one in my list.
Now, could you try disable / remove the wrong one?
Better export it first to a backup file...

**Comment by andreaceccanti** [comment]
Hi Maarten,

removing the intermediate CA from the Firefox CA bundle makes things work as expected.

The issue of the handshake failing on the validation a CA cert in the chain still holds. @golbi shouldn't CANL ignore CA certs in the incoming chain?

**Comment by maarten-litmaath** [comment]
Ciao Andrea,
at least we seem to have a workaround then...

**Comment by andreaceccanti** [comment]
> at least we seem to have a workaround then...

yep, 👍 , but not an easy one to apply for the casual user.

**Comment by maarten-litmaath** [comment]
They also can switch to Chrome or Safari for such workflows.

**Comment by golbi** [comment]
Andrea, Maarten,

Canl gets a cert chain to be validated. Usually one element long chain (EEC) but can be longer. That is AFAIU the normal procedure: infrastructure can setup its trust anchors to arbitrary level, and don't have to install all intermediary CA certs in the world. Canl validates a chain and chain's root element needs to be issued by any of the configured trust anchors. 

All in all I guess this feature request should be bit different:
"allow to turn on a validation mode, where canl stops validation and assumes the chain is valid, as soon as it finds the first element in chain which is issued by a trust anchor."

Adding an option to validate EEC only is much simpler, but don't know if it will bring more good than bad...

**Comment by maarten-litmaath** [comment]
Hi Krzysztof,
the way you formulated the feature request seems better indeed, thanks!

**Comment by andreaceccanti** [comment]
Hi Krzysztof,

> infrastructure can setup its trust anchors to arbitrary level, and don't have to install all intermediary CA certs in the world. Canl validates a chain and chain's root element needs to be issued by any of the configured trust anchors.

However, looking at the example above, the chain sent by the client contained the GEANT eScience Personal CA 4 certificate, which for our service is a trust anchor (i.e., that cert is included in the trust store used by the certificate validator).

CANL looks and validates the cert in the client chain (and fails) while it should have ignored that cert (and anything below it in the client chain), since the local trust store already contains a trust anchor for the GEANT eScience Personal CA4. This IMO should be the default behaviour, i.e. not require any flag.

Note that that what constitutes a trust anchors is still flexible and defined by the deployment, i.e. on the services side, by the certificates loaded by services for the certificate validator.

**Comment by andreaceccanti** [comment]
I am now observing problems with CANL on the client side and OpenSSL on the server side (the VOMS server),
and again the problems seems to be the wrong USERTRUST ca cert sent by the client. 
More detail on this [issue](https://issues.infn.it/jira/browse/VOMS-873) for the interested.

This to say that the OpenSSL-based VOMS server is showing the same supposedly buggy behaviour as the CANL library.

**Comment by andreaceccanti** [comment]
An update on this issue:

The problem is caused by the client certificate bundle being released by the Sectigo CA which contains a broken chain, so users should clean up and regenerate the p12. 

Once the client bundle is fixed, things work fine.

**Comment by golbi** [comment]
As it seems we have a new ticket in this area let me move discussion to it #116

**Comment by golbi** [comment]
@msalle I noticed that difference. The point is that canl theoretically (I'm just after refreshing my understanding of the code) should first try to enumerate all possible certificate paths from the provided arguments which ends up in a certificate issued by a trust anchor, then should try to validate all such paths, and succeed if any of the paths is valid. There is also one fallback if "intelligent" path building fails, then the given list of certificates is taken as is and tried to validate -> to get an error which will hopefully will make sense.

From both tickets it seems that something is broken in this algorithm. So I assume we have a common bug, or if two then close enough to share the same ticket :-)

So folks - the code is terribly complex in there (hacked BC code, which is terrible on its own, and was hacked - to have better error reporting and few bugs fixed). No chance that I will spot this issue just by using force. Could you please attach to either of the tickets certificates which allows for reproducing the problem? That is:
1. a full argument canl gets for verification, i.e. a list of certificates, noting which is the actual validated cert.
2. certificate(s) which are used as trust anchors (can be limited to the ones relevant of course).

Having that I should be able to locate the problem.
