### ISSUE TITLE
Compilation fails with Apache Commons-IO 2.9

### ISSUE THREAD

**Issue by ellert** [eu-emi/canl-java#111]
The version of commons-io (libcommons-io-java) in Debian was recently updated to version 2.11:
https://tracker.debian.org/pkg/commons-io

This with this change canl-java started to fail to compile.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998608

[ERROR] /<<PKGBUILDDIR>>/src/main/java/eu/emi/security/authn/x509/helpers/trust/OpensslTruststoreHelper.java:[80,17] <anonymous eu.emi.security.authn.x509.helpers.trust.OpensslTruststoreHelper$1> is not abstract and does not override abstract method accept(java.nio.file.Path,java.nio.file.attribute.BasicFileAttributes) in org.apache.commons.io.file.PathFilter

**Comment by ellert** [comment]
See:
https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/filefilter/IOFileFilter.html#accept-java.nio.file.Path-java.nio.file.attribute.BasicFileAttributes-

**Comment by golbi** [comment]
Closing, workaround known, proper fix with update to Java 8 will follow
