### ISSUE TITLE
NullPointerException via PemCredential when private key is password protected

### ISSUE THREAD

**Issue by lemora** [eu-emi/canl-java#114]
Hello caNL team,

when using the the PemCredential constructor with a `null`-valued `char[] keyPasswd` parameter and the key is password protected, a NullPointerException is thrown.

The associated JavaDoc states `May be null if the key is not encrypted`:
https://github.com/eu-emi/canl-java/blob/c543d07138552ca72168055a67df7354fd7ce552/src/main/java/eu/emi/security/authn/x509/impl/PEMCredential.java#L82

This behaviour is problematic, because knowing whether the key is encrypted would only be possible by loading the file and parsing the file's contents, which is the responsibility of this class.  Therefore, one would have to develop functionality that overlaps with PEMCredential in order to use the PEMCredential class correctly, which does not seem reasonable.

When instead using an empty byte array, it at least reports a helpful error message:
` java.io.IOException: Error decrypting private key: the password is incorrect or the PEM data is corrupted.`.

Regards
Lea

**Comment by golbi** [comment]
ok, will be fixed in next release
