### ISSUE TITLE
sortChain() method can return array with nulls

### ISSUE THREAD

**Issue by golbi** [eu-emi/canl-java#73]
This can happen if an input list of certificates contains duplicated entries. 

Related ticket: https://ggus.eu/index.php?mode=ticket_info&ticket_id=113859

**Comment by andreaceccanti** [comment]
Hi,
will you backport this fix to the 1.x branch as well?

Cheers,
A.

**Comment by golbi** [comment]
Hi Andrea,

No plans so far. Anyway the release with this bugfix won't be soon as there is no other higher priority thing fix. If you plan to have workaround this shouldn't harm much.

Cheers,
Krzysztof

**Comment by andreaceccanti** [comment]
Hi Krzysztof,
I agree there's no rush to release this, but when this will be released it would be good to have it also the in 1.x branch
