### ISSUE TITLE
bouncycastle 1.52

### ISSUE THREAD

**Issue by ellert** [eu-emi/canl-java#74]
Hi!

As you know I maintain the canl-java package in Fedora and EPEL.
The bouncycastle version in Fedora rawhide (the development version) has been updated to 1.52.
In this bouncycastle version there are some changes that causes canl-java not to compile.
In particular the scope of the classes org.bouncycastle.jce.provider.CertPathValidatorUtilities and org.bouncycastle.jce.provider.RFC3280CertPathUtilities have changed from "public class" to "class", which means that the classes in canl-java that inherit from them no longer compiles.

For build logs see: https://koji.fedoraproject.org/koji/taskinfo?taskID=10081257

Here is a link to the commit that makes the classes non-public:
https://github.com/bcgit/bc-java/commit/1d4d26ca76d3665f3bbe15cf0c7e0b3de40b8c6f

The commit log doesn't really explain why it was done.

I am not sure how to fix this.

**Comment by ellert** [comment]
I also asked bouncycstle upstream about this:
http://www.bouncycastle.org/jira/browse/BJA-546

Their reply was:
"The classes were never meant to be public.
Oh dear. Would you ask them to get in touch with us? If there's some generally useful functionality in there we would make it available somewhere. Perhaps not there though."

**Comment by ellert** [comment]
Hi!
I managed to make it work by copying and modifying some bouncycastle code:
http://pkgs.fedoraproject.org/cgit/canl-java.git/plain/canl-java-bc152.patch
I'm not creating a pull request for this patch, because it is a big hack and there are probably better ways to do it.

**Comment by golbi** [comment]
Hi,
Thanks for the patch. However, I'm also working on it and I'm pretty advanced. My goal is not to modify any BC code as it clearly leads to problems. Currently I'm on vacation, I'll get back to this next week and hopefully release new version based on 1.52.
