### ISSUE TITLE
CRL validation succeeds despite of expired CRL

### ISSUE THREAD

**Issue by gbehrmann** [eu-emi/canl-java#78]
Hi,

I have issues with the behaviour of CrlCheckingMode.IS_VALID when the CRL is expired. The JavaDoc states:

	/**
	 * If a CRL for CA which issued a certificate being validated
	 * is present and valid then the certificate must not be listed on the CRL.
	 * If the CRL is present but it is outdated (or anyhow else corrupted) then the validation fails. 
	 * If CRL is missing then validation is successful.
	 */
	IF_VALID,

That is, if the CRL is present but expired then the validation should fail. I have the following test code that I invoke with my proxy certificate:

    public class Main {
        public static void main(String[] args) throws CertificateException, KeyStoreException, IOException
        {
            PEMCredential credential = new PEMCredential(args[0], (char[]) null);
            X509CertChainValidator vff = new OpensslCertChainValidator(
                    "/etc/grid-security/certificates",
                    NamespaceCheckingMode.EUGRIDPMA_AND_GLOBUS, 60000,
                    new ValidatorParams(new RevocationParameters(CrlCheckingMode.IF_VALID, new OCSPParametes()), ProxySupport.ALLOW));

            ValidationResult result = vff.validate(credential.getCertificateChain());
            System.out.println(result);
        }
    }

The relevant CRL for the issuing CA is expired:

    $ openssl crl -in /etc/grid-security/certificates/1f0e8352.r0 -text| grep Update
        Last Update: Aug 26 11:03:47 2015 GMT
        Next Update: Sep 25 11:03:47 2015 GMT
    $ date
    Fre 25 Sep 2015 14:34:20 CEST

Yet the validation with the test program succeeds.

Single stepping through the code in a debugger does show that the CRL is loaded but ignored as it is expired. According to the JavaDoc above this should however have caused the validation to fail.

This was tested with both CANL 1.3.3 and 2.2.0 (we currently need CANL 1.3 due to BC dependencies in third party libraries).

**Comment by golbi** [comment]
There is a quite comprehensive test for this, however it is not testing expired CRLs (only otherwise invalid as badly signed). I'll try to create some similar test case and will see if it is reproduced.

**Comment by golbi** [comment]
OK, I can confirm this bug. Indeed the a present & outdated CRLs were always ignored.
