### ISSUE TITLE
Inconsistent default for infinite proxy path length

### ISSUE THREAD

**Issue by msalle** [eu-emi/canl-java#81]
There is an inconsistency between how an infinite proxy path length is encoded. In one place it's encoded as Integer.MAX_VALUE, in others as -1.
src/main/java/eu/emi/security/authn/x509/helpers/proxy/ProxyCertInfoExtension.java assumes that the default, infinite proxy path length is Integer.MAX_VALUE, see e.g. line 63
while on the other hand src/main/java/eu/emi/security/authn/x509/proxy/BaseProxyCertificateOptions.java assumes that the default, infinite proxy path length is -1, see e.g. line 61.
The result is that a proxy created using ProxyRequestOptions() with default parameters will get a proxy path length of actually -1 instead of infinite (which is actually absence of a pCPathLenConstraint).
The current workaround is to call setProxyPathLimit( Integer.MAX_VALUE ) on the created ProxyRequestOptions instance.

Best wishes,
Mischa

**Comment by golbi** [comment]
True. Unfortunately it is bit worse, as this setting is also used in proxy CSR generation API and it is used correctly there, i.e. only the documented -1 is handled correctly.

I'll fix it as follows: public API documentation and implementation will allow for both -1 AND MAX_VALUE to create unlimited proxies and proxy CSR. This shouldn't break the code which has your workaround and also fix the bug.

**Comment by msalle** [comment]
That sounds like a fine solution. Both values cannot reasonably mean an actual infinite path length.
We actually stumbled upon it for proxy CSR creation (https://github.com/ttomttom/aarc-portal/blob/master/ncsa-security-all-fork/ncsa-security-all/ncsa-security-common/ncsa-security-util/src/main/java/edu/uiuc/ncsa/security/util/pkcs/ProxyUtil.java#L95 and further)
