### ISSUE TITLE
caNL produces incompatible draft-RFC proxies

### ISSUE THREAD

**Issue by msalle** [eu-emi/canl-java#88]
draft-RFC (=GT3) proxies produces by the globus toolkit or C(++)-based VOMS have a different proxyCertInfo than the RFC proxies in case of non-infinite proxy pathlength constraint. In openssl.conf notation, a GT3 proxy cert info is of the form
> field1 = SEQUENCE:_proxy policy_
> field2 = EXPLICIT:1C,INTEGER:_proxy path length_

where _proxy policy_ and _proxy pathlength_ are of the same form as for RFC proxies.

For reference, the corresponding RFC proxy would have:
> field1 = INTEGER:_proxy pathlength_
> field2 = SEQUENCE:_proxy policy_

See e.g. https://github.com/globus/globus-toolkit/blob/globus_6_branch/gsi/proxy/proxy_ssl/source/library/proxycertinfo.c#L450 and https://github.com/italiangrid/voms/blob/master/src/sslutils/proxycertinfo.c#L276

In caNL-java, the problem is around lines https://github.com/eu-emi/canl-java/blob/master/src/main/java/eu/emi/security/authn/x509/helpers/proxy/ProxyGeneratorHelper.java#L240 where the same ProxyCertInfoExtension is added for both types of proxies.

The practical implication is that a draft-RFC proxy **with path-length constraint** created with voms-proxy-init2 or grid-proxy-init fails to verify with voms-proxy-init3.

**Comment by golbi** [comment]
I finally started to look at this. Can you provide bit more info:
1) Can you provide the legacy draft RFC? Or alternatively the formal notation of the draft RFC proxy extension? I don't know the openssl notation, I only guess that the field2 is explicitly tagged object with tag 0x1C, and the tagged object is INTEGER. Correct?

2) The most important - can you provide me with some example (can be naturally expired) draft proxy with path-length constraint so I can create a test case?

Thanks in advance

**Comment by msalle** [comment]
Hi,
thanks!
1) unfortunately there isn't any as far as I know. The tag is indeed an integer, but value is
[GT3_proxy.zip](https://github.com/eu-emi/canl-java/files/445902/GT3_proxy.zip)

 1 (the C is for context-specific, see e.g. https://www.openssl.org/docs/manmaster/crypto/ASN1_generate_nconf.html and look for EXPLICIT). The way it's defined in C-code you can see in https://ndpfsvn.nikhef.nl/viewvc/mwsec/trunk/lcmaps-plugins-verify-proxy/src/verify-proxy/verify-lib/src_internal/_verify_proxy_certinfo.c lines 75-79 for GT3, lines 67-71 for GT4. 
2) see the attached GT3 proxy without private key, with path-length 42 (0x2A).
If you have a voms-client2 lying around (still shipped with Debian as voms-clients or EPEL as voms-clients-cpp, or build from source from https://github.com/italiangrid/voms), you can create them using the `-proxyver 3 -path-length 42` options (the java-based voms-clients use canl-java). Alternatively use Globus' grid-proxy-init, using the `-draft -path-length 42 `options.

Just let me know if I can help further...
Cheers,
Mischa
